CC = g++

CFLAGS  = -Wall -std=c++11 -pthread 

TARGET = trabalho2


all: $(TARGET)

$(TARGET): $(TARGET).cpp
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).cpp
 	
clean:
	$(RM) $(TARGET)

# Makefile adaptado a partir do codigo fornecido pelo professor
