CC = g++

CFLAGS  = -Wall

TARGET = trabalho1


all: $(TARGET)

$(TARGET): $(TARGET).cpp
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).cpp
 	
clean:
	$(RM) $(TARGET)

# Makefile adaptado a partir do codigo fornecido pelo professor
